apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamforge.fullname" . }}-secrets
  labels:
    {{- include "streamforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.adminPassword | quote }}
  STREAMFORGE_DATABASE_URL: "postgres://{{ .Values.postgres.auth.coreUser }}:{{ .Values.postgres.auth.corePassword }}@{{ include "streamforge.fullname" . }}-postgres:5432/{{ .Values.postgres.auth.coreDatabase }}?sslmode=disable"
  STREAMFORGE_ALERTS_DATABASE_URL: "jdbc:postgresql://{{ include "streamforge.fullname" . }}-postgres:5432/{{ .Values.postgres.auth.alertsDatabase }}"
  STREAMFORGE_ALERTS_DATABASE_USER: {{ .Values.postgres.auth.alertsUser | quote }}
  STREAMFORGE_ALERTS_DATABASE_PASSWORD: {{ .Values.postgres.auth.alertsPassword | quote }}
